### ISSUE TITLE
Consider exporting constructors for the Tree type?

### ISSUE THREAD

**Issue by parsonsmatt** [jplatte/purescript-trees#6]
That the tree type is abstract makes working with it much more verbose and error-prone than I'd like. Would you be willing to expose the constructors to work with the `Tree` type directly?

**Comment by jonsterling** [comment]
I feel that there is great value in treating trees as an abstract type—this is the purpose of the views. However, since I sadly don't have time anymore to work on this library, I leave the decision entirely up to @jplatte and anyone who is really contributing to it.

**Comment by jplatte** [comment]
I would be okay with removing the views and exporting the types directly. I think having a breaking change when the tree representation changes shouldn't be that much of a problem in a language where even the core syntax frequently has deprecations and removals.

I'll still have to work through #4 though before I want to look at releasing this.

I will have a look at that as well as this issue later today or in the next few days (I guess I will have to rewrite pretty much everything I wrote :D).

**Comment by parsonsmatt** [comment]
I'm happy to provide a PR to help out with that!

I get the desire to treat trees abstractly over their underlying representation -- I think a more pleasant approach might be through type classes or the [first class module record trick](http://www.haskellforall.com/2012/07/first-class-modules-without-defaults.html). This might be entirely my unfamiliarity with using the view pattern pattern, of course.
